### PR TITLE
tr

### PR DESCRIPTION
**Pull request by kmlalpr**
I translated to turkish language.

### CODE REVIEW

**Comment by v-fedorov** [comment]
thanks for this!

Currently we are only configured to handle languages that are supported by bungie.
Once we make some modifications to support this PR I will let you know :)

**Comment by peterrobie** [comment]
@v-fedorov Would it be feasible to use the Google Translate API in the meantime?

**Comment by kmlalpr** [comment]
I didnt understand sir

iPhone'umdan gönderildi

5 Tem 2016 tarihinde 20:22 saatinde, Peter Robie <notifications@github.com> şunları yazdı:

**Comment by peterrobie** [comment]
Hi Kmlalpr,

What I was talking about was in reference to his comment "Currently we are only configured to handle languages that are supported by bungie."

I found a free translation API that might be able to resolve that issue. 
( https://tech.yandex.com/translate/ )

I haven't researched this particular service, but I would assume it would be a lot like the Google Translate API only free since the Google Translate API is not.

**Comment by SteffanLong** [comment]
Even if we used a translation API, the weapon, armor, and perk names would not be translated. This is why we currently only offer localization for languages supported by Bungie, because most of our strings are straight from their definitions.

**Comment by peterrobie** [comment]
Makes sense. Thanks @SteffanLong

**Comment by kmlalpr** [comment]
But in Turkish, we can use weapon names as english. Thorn will be thorn. No time to explain will be same like i said. But some explanations will be changed. "Most weapon used" will be " Sık kullanılan silah" etc. I can help you if you want. I also translated "Tower ghost for destiny" to turkish. 

iPhone'umdan gönderildi

5 Tem 2016 tarihinde 20:46 saatinde, Peter Robie <notifications@github.com> şunları yazdı:

**Comment by SteffanLong** [comment]
Oh, that makes sense. Can we assume that the majority of Turkish users will be able to understand weapon/armor/perk names in English, or should we allow an option to choose which language the Bungie definitions load as? We can offer two language selections, one for weapon/armor/perk names and one for the website strings, if that helps.

**Comment by kmlalpr** [comment]
Yeah! That is true. Sound is good. 

iPhone'umdan gönderildi

5 Tem 2016 tarihinde 21:07 saatinde, Steffan Long <notifications@github.com> şunları yazdı:

**Comment by SteffanLong** [comment]
@kmlalpr Should we add a second language selection for the Destiny armor and weapon information, or just default to English? I'm wondering if anyone will use Turkish translations for the website and a language besides English for the Destiny armor and weapon information.

**Comment by kmlalpr** [comment]
Weapon and Armor names will be English. We dont need to add language selection for armor and weapons. 

iPhone'umdan gönderildi

8 Tem 2016 tarihinde 05:32 saatinde, Steffan Long <notifications@github.com> şunları yazdı:

**Comment by SteffanLong** [comment]
Thank you for your translations! When you get a chance, can you take a look and see if anything needs to be adjusted?

**Comment by kmlalpr** [comment]
How can i translate? You didnt say it

iPhone'umdan gönderildi

10 Tem 2016 tarihinde 11:27 saatinde, Steffan Long <notifications@github.com> şunları yazdı:

**Pull request merged**
